python3 cli.py \
--method pet \
--pattern_ids 0 \
--data_dir ./data \
--model_type xlm-roberta \
--model_name_or_path xlm-roberta \
--task_name /home/am_derakhshan/fnlp/models/xlm-roberta/xlm-roberta-large \
--output_dir ./output \
--no_train \
--do_eval \
--no_distillation